default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: srlucky123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: clients_management_development
